name: flutter_website
publish_to: none
description: Smartnote, A GPW Offset brand
version: 1.1.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  animations: ^2.0.7
  url_launcher: ^6.1.10
  carousel_slider: ^4.2.1
  webview_flutter: ^4.0.6
  universal_html: ^2.2.1
  google_fonts: ^4.0.3
  responsive_framework: ^1.0.0
  font_awesome_flutter: ^10.5.0
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  motion: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/home/
    - assets/notebooks/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/product_sans_italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_italic.ttf
          style: italic
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Medium.ttf
          style: italic
